name: django_starter_app
version: '3.8'

services:  
  web:
    build:
      context: .
    ports:
    - "8000:8000" 
    command: ["sh", "./start.sh"]   
    volumes:
      - .:/app
    env_file:
      - .env    
    depends_on:
      - postgres_db

#database service
  postgres_db:
    restart: always
    image: postgres:16.3-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:     
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    
  adminer:
      image: adminer
      restart: always      
      ports:
        - "8080:8080"

 
volumes:
  postgres_data: